name: Testing Stuff

on:
  issues:
    types: [opened]

defaults:
  run:
    shell: pwsh
jobs:
  test_job:
    name: Test Job
    runs-on: windows-latest
    steps:
      - name: Get Information on the job.
        run: Get-Content $GITHUB_EVENT_PATH


