name: Testing Stuff

on:
  issues:
    types: [opened]

defaults:
  run:
    shell: pwsh
jobs:
  test_job:
    name: Test Job
    runs-on: windows-latest
    steps:
      - name: Dump GitHub context
        env:
          ISSUE_URL: ${{ github.event.issue.url }}
        run: echo "$ISSUE_URL"
