name: Testing Stuff

on:
  issues:
    types: [opened]

defaults:
  run:
    shell: pwsh
jobs:
  test_job:
    name: Test Job
    runs-on: windows-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
